### PR TITLE
New features and old fixes

### PR DESCRIPTION
**Pull request by ResetXD**
I added **timeout** command plus changed the path of `lib` folder to something more reasonable.

PS: This PR doesn't add anything *great* but it is there to *confirm* that this repository is open for contribution so i can work on other time consuming features.

### CODE REVIEW

**Comment by Ahmed3457** [comment]
Ty

**Comment by Ahmed3457** [comment]
sorry, but some errors occured bc of the import changes and the deletion of values.py bc that file is the config 
image

**Comment by ResetXD** [comment]
I tested everything before making a PR,
what python version are you on?

**Comment by ResetXD** [comment]
oh the `lib` folder accidentally got into `.gitignore` let me fix that

**Pull request merged**
